NieuwlandGeo/SLDReader

src/OlStyler.js
`let fill = {};` leaded to black-fill polygons with no `Fill` property in SLD.
=> Fix expressions always true in polygonStyle

src/OlStyler.js
Current PR add stroke-opacity in line/polygon symbolizer following the logic that has been used for fill in the polygonStyle function.
=> Add stroke opacity in OlStyler for polygon and line symbolizers

src/OlStyler.js, src/Reader.js, test/OlStyler.test.js
We fixed some bugs that appeared when we pulled the new textsymbolizer and tried using it.
At the stroke implementation for geometry type 'Point', we changed that Stroke is just set, if the width is bigger than 0.
Also, the created halo (stroke of Text-Style) in the textStyle-function is just set, if it is actually existent.
We had to do those both changes, because visual appearence did not match with the given SLD entrys.
The width of the halo also must be multiplied by 2, because u need the stroke on both sides of the letter, not just on one.
Other things were just typos or bugs we found while implementing.
Greets,
Alex
=> Bugfixes and add user layer

src/OlStyler.js
Creating new OL style instances has a noticeable performance overhead, so instead of creating a new OL Style instance within each invocation of OlStyler, use a WeakMap to return the same OL style instance if the SLD symbolizer object is the same.
This only happens for point, polygon, and line symbolizers, because they are constant and do not depend on feature attributes. Text symbolizers are not cached in this manner, because they depend on feature properties.
=> Use WeakMap to cache OL style instances

src/Filter.js, src/OlStyler.js, src/Utils.js, test/Filter.test.js
The filter test function tests a filter object against a feature's properties object. In OpenLayers it's (much!) faster to read a specific feature property directly than to get a feature's properties and accessing the property you want. This is, because OpenLayers feature.getProperties() uses Object.assign under the hood, while direct property access reads from the feature property object directly.
Therefore, the filterSelector function has been changed to use a getProperty function instead of a getProperties function.
=> Optimize filterSelector performance

docs/_layouts/default.html, docs/assets/benelux.js, docs/assets/benelux.json, docs/assets/sld-benelux.xml, docs/assets/sldreader.js, docs/benelux.html, docs/grenzen.html, src/OlStyler.js, src/Utils.js, src/constants.js, test/OlStyler.test.js, test/data/externalgraphic.sld.js
In this pull request, external graphic icons are put into an image cache after load, so the correct scale can be calculated from the width and height of the loaded image.
With this, the parameter Size works as expected within a PointSymbolizer that uses an ExternalGraphic.
=> Cache externalgraphic icons

docs/assets/sldreader.js, src/OlStyler.js
This pull request fixes a few issues with how the Size parameter is applied inside a Graphic element.
* When using a Mark, the Size parameter now correctly sets the diameter (or height in case of a square).
* When using an ExternalGraphic, the image is scaled so the height equals the given Size.
=> Fix sld graphic scaling

src/OlStyler.js, test/OlStyler.test.js
There was a typo in test causing it's passing, while it shouldn't pass. Also fixed code to make this fixed test passing.
=> Fix typo in test `creates point style`

src/OlStyler.js, src/Reader.js, src/Utils.js
Hi,
i made it possible to use external graphics as pattern background for polygons. 
Example sld:
`
<sld:PolygonSymbolizer>
<sld:Fill>
<sld:GraphicFill>
<sld:Graphic>
<sld:ExternalGraphic>
<sld:OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAj0lEQVR4Xu2RsQ3AQAwCPzNlp+y/wSefkoIWg7CEi5MoTqzn3ts567zvLowLr4CaV0DNfwHnZCyAkBWm8QqoeYaAczIWQMgK03gF1DxDwDkZCyBkhWm8AmqeIeCcjAUQssI0XgE1zxBwTsYCCFlhGq+AmmcIOCdjAYSsMI1XQM0zBJyTsQBCVpjGK6Dm9gIvxmrUOF2e6O8AAAAASUVORK5C"></sld:OnlineResource>
<sld:Format>image/png</sld:Format>
</sld:ExternalGraphic>
<sld:Opacity>1.0</sld:Opacity>
<sld:Size>48.0</sld:Size>
<sld:Rotation>0.0</sld:Rotation>
</sld:Graphic>
</sld:GraphicFill>
<sld:CssParameter …
=> Support external graphic as fill for polygons

src/OlStyler.js, src/Reader.js, test/OlStyler.test.js, test/Reader.test.js, test/data/test.sld.js
Allows stacking shapes (like multiple PointSymbolizer in the same rule) allowing to do more complex symbols and shapes. Also adds `wellknown` `hexagon` and `octagon` (used in QGIS)
=> Multiple shapes

README.md, docs/assets/sldreader.js, src/olEvaluator.js, src/styles/pointStyle.js, src/styles/textStyle.js, test/OlStyler.test.js, test/data/dynamic.sld.js
This pull request addresses two issues with label rotation within PointPlacement section.
* Angles are now properly converted to radians used by OpenLayers.
* It's possible to use ogc:PropertyName with a label rotation element.
=> Fix label rotation

src/styles/static.js, src/styles/textStyle.js, test/OlStyler.test.js, test/data/textSymbolizer.sld.js
This pull request fixes a fatal crash at runtime in the generated style function when using a TextSymbolizer without an (optional) LabelPlacement element.
=> Fix handling TextSymbolizer without LabelPlacement

docs/assets/sldreader.js, src/Reader/index.js, src/styles/textStyle.js, test/OlStyler.test.js, test/data/textSymbolizer-cdata.sld.js, test/data/textSymbolizer-dynamic.sld.js
This pull request fixes two TextSymbolizer bugs:
* Whitespace-only CDATA text is stripped out of the label.
* Polygon labels using a numeric property value cause an error in the style function.
Fixes #68
=> Fix labeling regressions

docs/assets/sldreader.js, src/styles/graphicStrokeStyle.js
This pull request fixes a bug where graphic stroke marks are offset relative to the line geometries in environments that have a device to css pixel ratio different from 1, like mobile devices or on desktop environments that use font scaling.
=> Take pixelRatio into account for GraphicStroke

src/styles/simpleStyles.js, src/styles/wellknown.js, test/OlStyler.test.js
Casts strings to numbers to provide valid argument types for styles.
=> Cast string to number, solves #73

docs/assets/sldreader.js, src/styles/polygonStyle.js, test/OlStyler.test.js, test/data/poly-graphic-fill-and-stroke.js
This pull request fixes an issue where a Stroke is not rendered for polygon symbolizers that also have a GraphicFill.
=> Fix missing polygon stroke when using GraphicFill

docs/assets/sldreader.js, src/Utils.js, test/Utils.test.js
If an SLD contains a rule with an ElseFilter before another valid rule, the symbolizer of both rules are rendered.
This pull request fixes the handling of rules with an ElseFilter, so rules with an ElseFilter are never drawn if any other rule passes.
=> Fix ElseFilter evaluation

docs/assets/sldreader.js, rollup.config.js, src/styles/polygonStyle.js
This PR fixes a bug where polygon graphic fills did not take device pixel ratio into account, resulting in image fills that are a factor of 2 or 3 smaller than intended.
=> Fix polygon graphic fill scaling on mobile devices

docs/assets/sldreader.js, src/OlStyler.js, test/OlStyler.test.js, test/data/simple-line-symbolizer.sld.js
This fixes issue #91 where a LineSymbolizer is not applied to the outline of polygon features.
=> Apply LineSymbolizer to polygon outlines

docs/assets/sldreader.js, src/OlStyler.js, src/imageCache.js, test/OlStyler.test.js, test/data/externalgraphic.sld.js
This PR fixes the problem where the imageLoadedCallback of a style function did not get called if another style function already triggered a load for an ExternalGraphic image with the same image url.
Fixes #95
=> Fix image loaded callback

docs/assets/sld-provincies.xml, docs/assets/sldreader.js, src/styles/textStyle.js, test/OlStyler.test.js, test/data/textSymbolizer.sld.js
Implement AnchorpointX/Y label placement for text.
Note that this is only an approximation, because OpenLayers only supports left/right/top/bottom/center text aligment.
Implements #99
=> Implement anchor point for TextSymbolizer

docs/assets/sldreader.js, src/OlStyler.js, src/styles/geometryCalcs.js, src/styles/graphicStrokeStyle.js, src/styles/linePointStyle.js, src/styles/polygonPointStyle.js, test/OlStyler.test.js, test/data/simple-point-symbolizer.sld.js
Fixes #101 
This PR fixes the case where a PointSymbolizer is ignored when used on a (Multi)Line/Polygon geometry.
According to the SLD spec:
> In this case, if a line, polygon, 
or raster geometry is used with this Symbolizer, then the semantic is to use the centroid 
of the geometry, or any similar representative point.
I have interpreted 'representative point' as follows:
* For a LineString, the point is placed in the middle of the line string.
* For a MultiLineString, a point is placed in the middle of each segment.
* For a Polygon, the point is placed using OpenLayers `getInteriorPoint` method which is the same point used for text label placement.
* For a MultiPolygon, a point is placed on each part separately.
=> Point symbolizer for line polygon

src/Filter.js, src/Reader/filter.js, test/Filter.test.js, test/Reader.Filter.test.js
This PR fixes several issues with comparison operations within filters.
* Comparison operators now support comparing string values.
* Comparisons now use the attribute `matchCase` on comparison operators (default: true --> case sensitive comparison).
* Improve handling of null values: a comparison will always return false when a feature attribute is null or undefined.
=> Fix comparisons

docs/assets/hoogspanning.js, docs/assets/sld-external-graphic-mark.xml, docs/assets/sld-graphic-mark-placement.xml, docs/assets/sldreader.js, docs/hoogspanning.html, src/constants.js, src/styles/geometryCalcs.js, src/styles/graphicStrokeStyle.js, src/styles/linePointStyle.js, test/Reader.test.js, test/data/graphicstroke-vendoroption.sld.js
* Fix bug: according to the SLD spec, the horizontal center line of ExternalGraphic markers should follow the line string. Old behavior was to let the vertical center line follow the line string.
* Implement two QGIS vendorOptions for ExternalGraphic placement: firstPoint and lastPoint. Also added a demo page to demonstrate.
Fixes #116
=> Graphicstroke placement

docs/assets/sldreader.js, src/styles/graphicStrokeStyle.js
Fixes a crash that happens when you a GraphicStroke symbolizer is applied to a MultiLine or MultiPolygon geometry.
Fixes #119.
=> Fix GraphicStroke crash on multipart geometries

docs/assets/sldreader.js, src/Reader/index.js, test/Reader.test.js, test/data/test.sld.js
* Parses Abstract and Title elements (which are part of the SLD 1.0.0 spec).
* Handles possible case where FeatureTypeStyles are not present.
Fixes #83
Fixes #123
=> Parsing improvements

.eslintrc.json, docs/assets/sldreader.js, src/styles/pointStyle.js, test/OlStyler.test.js
This PR fixes #132 where a point symbolizer does not render points in a layer with mixed point/line/polygon geometries.
=> Point not rendered in mixed geometry layer

docs/assets/sld-provincies.xml, docs/assets/sldreader.js, src/styles/polygonStyle.js, src/styles/wellknown.js
This PR improves the visual clarity of polygon graphic fills with mark symbols. It also adds `line` and `slash` symbolizers and extends the `x` symbolizer to cover the entire symbol square space.
=> Graphicfill improvements

docs/api.md, docs/assets/sldreader.js, src/OlStyler.js, src/index.js, src/styles/linePointStyle.js, src/styles/polygonPointStyle.js, test/OlStyler.test.js
Add a new function `createOlStyle` to turn a single symbolizer in a rule into a static OpenLayers style array.
=> Create ol style

docs/assets/sldreader.js, src/OlStyler.js, src/Reader/index.js, src/olEvaluator.js, src/styles/graphicStrokeStyle.js, src/styles/pointStyle.js, src/styles/textStyle.js, test/Reader.test.js, test/data/dynamic-polygon-symbolizer.sld.js, test/data/graphicstroke-vendoroption.sld.js, test/data/static-polygon-symbolizer.sld.js, test/data/test.sld.js
A big refactoring of SLD parsing code and the corresponding SLD object data structure.
Main changes:
* Added type hints for values, so numeric properties will be marked as such.
* Simplified expression objects -> expressions with one child will be replaced with the child expression. Expressions that do not depend on feature properties will be simplified as much as possible.
* SVGParameters can be dynamic (type: 'propertyname') (support in ol styler function follows later).
=> Rework data stuctures

README.md, docs/api.md, docs/assets/benelux.js, docs/assets/dynamic-styling.js, docs/assets/sld-dynamic-styling.xml, docs/assets/sldreader.js, docs/benelux.html, docs/dynamic-styling.html, docs/grenzen.html, docs/hoogspanning.html, src/Reader/index.js, src/olEvaluator.js, src/styles/dynamicStyles.js, src/styles/graphicStrokeStyle.js, src/styles/lineStyle.js, src/styles/pointStyle.js, src/styles/polygonStyle.js, src/styles/simpleStyles.js, src/styles/styleUtils.js, src/styles/textStyle.js, src/styles/wellknown.js, test/OlStyler.test.js, test/Reader.test.js, test/data/dynamic-line-symbolizer.sld.js, test/data/dynamic-point-symbolizer.sld.js, test/data/dynamic-text-symbolizer.sld.js, test/data/empty-polygon-symbolizer.sld.js, test/data/empty-svg-parameters.sld.js, test/data/static-polygon-symbolizer.sld.js, test/olEvaluator.test.js
This branch enables dynamic (`ogc:PropertyName`) values for style properties (`SvgParameter`) inside symbolizers.
Note: this does not work for Marks inside a GraphicStroke or GraphicFill.
=> Dynamic symbolizer values

docs/assets/sld-benelux.xml, docs/assets/sldreader.js, src/styles/pointStyle.js, src/styles/textStyle.js, test/OlStyler.test.js, test/data/dynamic.sld.js, test/data/textSymbolizer.sld.js
This branch adds support for `Displacement` inside `Graphic` elements.
Also included is a fix for `DisplacementY` for text labels: positive displacement now shifts the label upwards instead of downwards.
=> Add support for graphic displacement

docs/assets/dynamic-styling.js, docs/assets/sld-dynamic-styling.xml, docs/assets/sldreader.js, src/styles/pointStyle.js, test/OlStyler.test.js, test/data/dynamic-point-symbolizer.sld.js
This PR fixes an issue where (dynamic) rotation and displacement properties were not set on graphic Marks if one or more SvgParameters also have dynamic values.
=> Fix dynamic style values

.prettierignore, docs/_includes/head_custom.html, docs/api.md, docs/assets/mark-gallery.css, docs/assets/mark-gallery.js, docs/assets/ol.js, docs/assets/sldreader.js, docs/mark-gallery.html, src/styles/static.js, src/styles/wellknown.js, test/OlStyler.test.js
This pull request fixes disappearing mark symbols like star and cross after upgrading to OpenLayers v9.0.0. The issue was caused by the removal of the `.radius1` property on the `RegularShape` style class.
This fix should be backwards compatible with earlier OpenLayers versions.
=> Fix ol9 regularshape

docs/assets/sldreader.js, src/styles/geometryCalcs.js, src/styles/graphicStrokeStyle.js, src/styles/linePointStyle.js, test/geometryCalcs.test.js
This PR fixes a crash that occurs when using a point symbolizer for linestrings shorter than 0.1 map units.
=> Fix midpoint calculation

docs/assets/sldreader.js, src/Reader/index.js, test/Filter.test.js, test/Reader.test.js, test/data/graphicstroke-with-comments.sld.js, test/data/textSymbolizer-cdata.sld.js
This PR fixes handling of comments in SLD xml:
* Reader does not throw if there's a comment before the root element.
* Reader ignores comment nodes inside SLD elements that hold a (text) value.
Additionally: Reader will now throw if the root node of the SLD xml is not a `StyledLayerDescriptor`.
=> Ignore comments

docs/assets/sldreader.js, src/Reader/index.js, test/Reader.test.js, test/data/test11.sld.js
Parse Title and Abstract from SLD v1.1.0 Description elements and add them as properties to the parent element.
Example:
```xml
<se:Rule>
<se:Name>Other</se:Name>
<se:Description>
<se:Title>Other provinces</se:Title>
<se:Abstract>This rule matches all other provinces</se:Abstract>
</se:Description>
...
</se:Rule>
```
Results in 
```
rule.name     --> "Other"
rule.title    --> "Other provinces"
rule.abstract --> "This rule matches all other provinces"
```
=> Parse SLD 1.1 Description elements

README.md, docs/assets/sldreader.js, src/Filter.js, src/OlStyler.js, src/Utils.js, src/olEvaluator.js, src/styles/dynamicStyles.js, src/styles/graphicStrokeStyle.js, src/styles/linePointStyle.js, src/styles/lineStyle.js, src/styles/pointStyle.js, src/styles/polygonPointStyle.js, src/styles/polygonStyle.js, src/styles/textStyle.js, test/Filter.test.js, test/Utils.test.js, test/olEvaluator.test.js
Replace getProperty in function signatures with context object containing
* A `getProperty(feature, propertyName)` function.
* A `getId(feature)` function.
* A `resolution` property with current resolution in ground units in metres / pixel.
=> Introduce context

docs/assets/sld-vector-tile.xml, docs/assets/sldreader-standalone.js, docs/assets/vector-tile.js, docs/vector-tile.html, olGlobals.mjs, src/functions/builtins/index.js, src/functions/helpers.js, src/olEvaluator.js, src/styles/linePointStyle.js, src/styles/polygonPointStyle.js
Fix bugs and crashes when applying a generated style function to a vector tile layer, which uses RenderFeature instead of Feature internally.
=> Handle renderfeature
